[target]
column = "UNITS"

[impute]
BRITTLE_STALK = 5.0
PLANT_HEIGHT = 6.0

[features]
pca_inputs1 = ["PRODUCT_AGE", "PROTECTION_SCORE", "DROUGHT_TOLERANCE", "BRITTLE_STALK", "PLANT_HEIGHT", "RELATIVE_MATURITY", "AGE_X_PROTECTION", "HEIGHT_X_MATURITY"]
pca_inputs = ["PRODUCT_AGE", "DROUGHT_TOLERANCE", "BRITTLE_STALK", "PLANT_HEIGHT", "RELATIVE_MATURITY", "AGE_X_PROTECTION", "HEIGHT_X_MATURITY"]
final1 = ["PRODUCT_AGE", "PROTECTION_SCORE", "DROUGHT_TOLERANCE", "BRITTLE_STALK", "PLANT_HEIGHT", "RELATIVE_MATURITY", "AGE_X_PROTECTION", "HEIGHT_X_MATURITY", "IS_NEW_PRODUCT", "PCA1", "PCA2", "STATE_California", "STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT", "LIFECYCLE_ESTABLISHED"]
final2 = ["PRODUCT_AGE", "DROUGHT_TOLERANCE", "BRITTLE_STALK", "PLANT_HEIGHT", "RELATIVE_MATURITY", "AGE_X_PROTECTION", "HEIGHT_X_MATURITY", "IS_NEW_PRODUCT", "PCA1", "PCA2", "STATE_California", "STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT", "LIFECYCLE_ESTABLISHED"]
final3 = ["PRODUCT_AGE", "DROUGHT_TOLERANCE", "BRITTLE_STALK", "PLANT_HEIGHT", "RELATIVE_MATURITY", "AGE_X_PROTECTION", "HEIGHT_X_MATURITY", "IS_NEW_PRODUCT", "PCA1", "PCA2", "STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT"]
final = ["PRODUCT_AGE", "PREVIOUS_UNITS", "DROUGHT_TOLERANCE", "BRITTLE_STALK", "PLANT_HEIGHT", "RELATIVE_MATURITY", "AGE_X_PROTECTION", "HEIGHT_X_MATURITY", "STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT"]
final0 = ["PRODUCT_AGE", "PRODUCT_encoded", "PREVIOUS_UNITS", "IS_NEW_PRODUCT", "STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT"]
id_columns = ["PRODUCT", "STATE", "LIFECYCLE"]

[categorical]
columns = ["PRODUCT", "STATE", "LIFECYCLE"]
one_hot_columns_flat1 = ["STATE_California", "STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT", "LIFECYCLE_ESTABLISHED"]
one_hot_columns_flat = ["STATE_Illinois", "STATE_Iowa", "STATE_NewYork", "STATE_Texas", "LIFECYCLE_EXPANSION", "LIFECYCLE_INTRODUCTION", "LIFECYCLE_PHASEOUT"]

[xgb_params]
n_estimators = 200
max_depth = 5
learning_rate = 0.05
subsample = 0.8

[input]
data_path = "data/case_study_data.csv"

[output]
base_model_path = "data/models/base_model.pkl"
base_scaler_path = "data/models/base_scaler.pkl"
residue_model_path = "data/models/residue_model.pkl"
residue_ohe_path = "data/models/residue_ohe.pkl"
pca_path = "data/models/base_pca.pkl"
features_path = "data/models/xgb_features.pkl"
cat_path = "data/models/xgb_cat.pkl"
app_path = "data/models/residual_app.pkl"